[workspace]
resolver = "2"
members = [
    "tf_r2r",
    "tf_roslibrust",
    "tf_rosrust",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/smilerobotics/tf_rosrust"
authors = [
    "Arjo Chakravarty <arjo129@gmail.com>",
    "Michael Maerz <maerz@magazino.eu>",
    "Mitsuharu Kojima <kojima@smilerobotics.com>",
]
keywords = ["transforms", "robotics", "ROS", "tf"]
categories = ["science::robotics"]

[workspace.dependencies]
futures = "0.3"
nalgebra = "0.30"
r2r = "0.9"
rosrust = "0.9"
thiserror = "1.0"
tokio = "1"
